### ISSUE TITLE
Investigate IllegalStateException: UT000127: Response has already been sent

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-quarkus#10]
The example project works fine but logs the following exceptions:

```
Caused by: java.io.IOException: java.lang.IllegalStateException: UT000127: Response has already been sent
	at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:249)
	at com.vaadin.flow.server.communication.PwaHandler.lambda$init$b8085539$1(PwaHandler.java:87)
	at com.vaadin.flow.server.communication.PwaHandler.handleRequest(PwaHandler.java:132)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
	... 44 more
Caused by: java.lang.IllegalStateException: UT000127: Response has already been sent
	at io.undertow.server.HttpServerExchange.writeBlocking(HttpServerExchange.java:1001)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:236)
	... 47 more
```

Verify whether this breaks something or not; if not then perhaps the exception should be suppressed.

**Comment by mvysny** [comment]
Bummer: Undertow reuses exceptions in the `UndertowMessages` class: the stack-trace might therefore be completely bogus. Also, it's it's not easy to reproduce the issue - sometimes the exception is not logged at all.
