### ISSUE TITLE
Vaadin Push

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-quarkus#12]
```
2021-01-22 10:29:14,542 WARN  [org.atm.cpr.AsynchronousProcessor] (executor-thread-2) Websocket protocol not supported
```

Enable support for Vaadin Push:

* Either via websockets (there's a Quarkus Extension for that)
* Or long-polling

**Comment by mvysny** [comment]
Adding undertow-websockets did seemingly nothing, so did forcing JSR356 impl via `servletContext.setInitParameter("org.atmosphere.cpr.asyncSupport", "org.atmosphere.container.JSR356AsyncSupport");`. 

However, via debugging I have learned that `JSR356AsyncSupport` fails to initialize at `JSR356AsyncSupport:53` by throwing `java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null`. Needs to investigate.

**Comment by mvysny** [comment]
The full stack trace is:

```
2021-01-22 16:28:59,145 WARN  [org.atm.cpr.DefaultAsyncSupportResolver] (Quarkus Main Thread) Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: {}: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2092)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.flow.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:220)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(JSR356WebsocketInitializer.java:184)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.init(JSR356WebsocketInitializer.java:149)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.contextInitialized(JSR356WebsocketInitializer.java:118)
	at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized(ServletContextListeners.java:42)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:188)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:218)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$10$1.call(UndertowDeploymentRecorder.java:554)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:253)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:508)
	at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy_0(UndertowBuildStep$build-649634386.zig:2186)
	at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy(UndertowBuildStep$build-649634386.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:180)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:53)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42)
	... 41 more
```

I've tried to explicitly configure QuarkusVaadinServlet to support async, via

```
        servletProducer.produce(ServletBuildItem.builder(QuarkusVaadinServlet.class.getName(), QuarkusVaadinServlet.class.getName())
                .addMapping("/*").setAsyncSupported(true).build());
```

did not help.

**Comment by mvysny** [comment]
Asked on SO: https://stackoverflow.com/questions/65847175/quarkusatmosphere-fails-with-unable-to-configure-jsr356-at-that-stage

**Comment by mvysny** [comment]
While the websocket issue is resolved, it is possible to use LONG_POLLING to use Vaadin push: `@Push(transport = Transport.LONG_POLLING)`.

**Comment by mvysny** [comment]
Tatu pointed me towards this, I'll analyze: https://github.com/quarkusio/quarkus-http/blob/master/websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/AddEndpointServlet.java#L40

**Comment by mvysny** [comment]
Further investigation: the `io.undertow.websockets.jsr.Bootstrap.handleDeployment()` is called, but the `io.undertow.websockets.jsr.WebSocketDeploymentInfo` is null and thus websockets are not initialized :thinking:

**Comment by mvysny** [comment]
The `UndertowWebsocketRecorder.createDeploymentInfo()` produces `WebSocketDeploymentInfo`, however the Recorder machinery is not clear to me: I don't know when the Recorders are called, and how does the resulting `WebSocketDeploymentInfo` instance end up in `deploymentInfo.getServletContextAttributes()`.

**Comment by mvysny** [comment]
Found it! https://github.com/quarkusio/quarkus/blob/master/extensions/undertow-websockets/deployment/src/main/java/io/quarkus/undertow/websockets/deployment/UndertowWebsocketProcessor.java

The websockets-deployment will call the recorder and place the resulting `WebSocketDeploymentInfo` correctly, by emitting  `ServletContextAttributeBuildItem`. However, nothing is done if:

```
 if (annotatedEndpoints.isEmpty() &&
                endpoints.isEmpty() &&
                config.isEmpty()) {
            return null;
        }
```

**Comment by mvysny** [comment]
2. can be remedied by introducing a dummy websocket config class:

```
public class WebsocketConfig implements ServerApplicationConfig {
    @Override
    public Set<ServerEndpointConfig> getEndpointConfigs(Set<Class<? extends Endpoint>> endpointClasses) {
        return new HashSet<>();
    }

    @Override
    public Set<Class<?>> getAnnotatedEndpointClasses(Set<Class<?>> scanned) {
        return new HashSet<>();
    }
}
```

**Comment by mvysny** [comment]
However, for some reason websocket connection is not established and the client falls back to long-polling. This can be seen both in the browser's Network tab, and also in JS console:

```
Establishing push connection client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:944:179
Invoking executeWebSocket, using URL: ws://localhost:8080/?v-r=push&v-uiId=1&v-pushId=2f676978-0a72-4c35-828f-cec269384d3a&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json; charset=UTF-8&X-atmo-protocol=true vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: websocket.onopen vaadinPush.js:3268:28
Websocket successfully opened vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: websocket.onclose vaadinPush.js:3268:28
Websocket closed, reason: Normal closure; the connection successfully completed whatever purpose for which it was created. - wasClean: false vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Firing onClose (closed case) vaadinPush.js:3268:28
Push connection closed client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:1027:16627
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Request already closed, not firing onClose (closed case) vaadinPush.js:3268:28
Websocket failed on first connection attempt. Downgrading to long-polling and resending vaadinPush.js:3268:28
Push connection using primary method (websocket) failed. Trying with long-polling client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:199:20
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 2 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 3 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 4 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 2 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Firing onOpen vaadinPush.js:3268:28
Push connection established using long-polling
```

**Comment by mvysny** [comment]
Pushed preliminary support for Push + demo route into the example project: 3e02fbc022556fa3729eccdd09fc83aea6767aa1

**Comment by mvysny** [comment]
Running tests will now log a lot of
```
Caused by: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:53)
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42)
        ... 93 more
```
investigate.

**Comment by mvysny** [comment]
No idea what's going on here. `com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect()` is called properly on server-side and is stopped in a breakpoint. However the browser already claims that `Websocket closed, reason: Normal closure` and falls back to long polling. There must be something on the server-side closing the websocket connection...

**Comment by mvysny** [comment]
Vaadin Push + long polling works, closing.
