### ISSUE TITLE
Vaadin Push doesn't use WebSockets and falls back to long polling

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-quarkus#17]
The Browser javascript tab reveals the following log:

```
Establishing push connection client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:944:179
Invoking executeWebSocket, using URL: ws://localhost:8080/?v-r=push&v-uiId=1&v-pushId=2f676978-0a72-4c35-828f-cec269384d3a&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json; charset=UTF-8&X-atmo-protocol=true vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: websocket.onopen vaadinPush.js:3268:28
Websocket successfully opened vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: websocket.onclose vaadinPush.js:3268:28
Websocket closed, reason: Normal closure; the connection successfully completed whatever purpose for which it was created. - wasClean: false vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Firing onClose (closed case) vaadinPush.js:3268:28
Push connection closed client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:1027:16627
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Request already closed, not firing onClose (closed case) vaadinPush.js:3268:28
Websocket failed on first connection attempt. Downgrading to long-polling and resending vaadinPush.js:3268:28
Push connection using primary method (websocket) failed. Trying with long-polling client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:199:20
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 2 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 3 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 4 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 2 vaadinPush.js:3268:28
Tue Jan 26 2021 16:26:48 GMT+0200 (Eastern European Standard Time) Atmosphere: Firing onOpen vaadinPush.js:3268:28
Push connection established using long-polling
```

You can also see in the Network tab that a long-polling request is opened by the Vaadin client for some reason.

No idea what's going on here. `com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect()` is called properly on server-side and is stopped in a breakpoint. However the browser already claims that `Websocket closed, reason: Normal closure` and falls back to long polling. There must be something on the server-side closing the websocket connection...

Also see #12 for more details.

**Comment by mvysny** [comment]
Enabling a debug logging via the following in `application.properties`
```
quarkus.log.category."org.atmosphere".min-level=DEBUG
quarkus.log.category."org.atmosphere".level=DEBUG
```
revealed the following exception in the websocket endpoint onOpen() method:
```
2021-02-05 14:02:46,338 DEBUG [org.atm.con.JSR356Endpoint] (vert.x-eventloop-thread-11) Problem in web socket session: java.lang.NullPointerException
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:129)
	at io.undertow.websockets.jsr.EndpointSessionHandler.connected(EndpointSessionHandler.java:130)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.accept(JsrWebSocketFilter.java:128)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.accept(JsrWebSocketFilter.java:125)
	at io.undertow.websockets.jsr.handshake.Handshake$1.accept(Handshake.java:141)
	at io.undertow.vertx.VertxHttpExchange$10$1.run(VertxHttpExchange.java:869)
	at io.undertow.vertx.VertxHttpExchange$10.handle(VertxHttpExchange.java:873)
	at io.undertow.vertx.VertxHttpExchange$10.handle(VertxHttpExchange.java:858)
	at io.vertx.core.net.impl.ConnectionBase.lambda$wrap$1(ConnectionBase.java:184)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
```
This is almost certainly the cause of this issue.

**Comment by mvysny** [comment]
Reported upstream as https://github.com/Atmosphere/atmosphere/issues/2427

**Comment by mvysny** [comment]
PR: https://github.com/urosporo/vaadin-quarkus-extension-parent/pull/7
