### ISSUE TITLE
Take `flow-build-info.json` into use

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-quarkus#2]
Currently `flow-build-info.json` file is ignored by Vaadin for unknown reason, even if it's generated by Vaadin plugin and present in `target/classes/META-INF/VAADIN/config/flow-build-info.json`. My hunch is that Vaadin doesn't use context class loader, but this needs to be verified.

This is the reason why there's the following in web.xml:

```xml
        <init-param>
            <param-name>project.basedir</param-name>
            <param-value>/home/mavi/work/inacta/vaadin-quarkus</param-value>
        </init-param>
```

Without the above stanza in web.xml, Vaadin initialization will fail:

```
2020-12-22 16:59:03,834 ERROR [io.und.req.io] (executor-thread-4) Exception handling request 310f94c1-5596-4340-ab15-d78bb8230b2a-6 to /VAADIN/static/server/workbox/workbox-sw.js: java.lang.IllegalStateException: The compatibility mode is explicitly set to 'false', but there are neither 'flow-build-info.json' nor 'webpack.config.js' file available in the project/working directory. Ensure 'webpack.config.js' is present or trigger creation of 'flow-build-info.json' via running 'prepare-frontend' Maven goal.
	at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:465)
	at com.vaadin.flow.server.DeploymentConfigurationFactory.lambda$readBuildInfo$1ac205d3$1(DeploymentConfigurationFactory.java:192)
	at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:320)
```

**Comment by mvysny** [comment]
This is the reason why there's `@WebInitParam(name = FrontendUtils.PROJECT_BASEDIR, value = "/home/mavi/work/inacta/vaadin-quarkus")` in `MyServlet`.

**Comment by mvysny** [comment]
After this issue is resolved, `MyServlet.java` may be removed (which means that DevModeInitializer may be removed as well).

**Comment by mvysny** [comment]
Indeed it's a problem in Vaadin: DeploymentConfigurationFactory uses `DeploymentConfiguration.class.getClassLoader()` which doesn't discover app-specific resources, as the following screenshot shows:


![Screenshot from 2020-12-22 16-45-27](https://user-images.githubusercontent.com/254091/102900658-47b77580-4475-11eb-8e01-1c05415ea163.png)

The `tokenResource` list is empty; while `Collections.list(Thread.currentThread().getContextClassLoader().getResources(tokenResource))` works correctly and returns the path to `file:/home/mavi/work/inacta/vaadin-quarkus/target/classes/META-INF/VAADIN/config/flow-build-info.json`.

**Comment by mvysny** [comment]
Filed a bug upstream: https://github.com/vaadin/flow/issues/9713

**Comment by mvysny** [comment]
Unfortunately class shadowing trick doesn't work for some reason. The only solution is to either have this fixed in Vaadin 14 upstream, or use Vaadin 19 and use the new Lookup API.

**Comment by mvysny** [comment]
Vaadin 19 Lookup API indeed helps: the following ResourceProvider fixes the issue:
```java
public class QuarkusResourceProvider implements ResourceProvider {
    @Override
    public URL getApplicationResource(String path) {
        return Thread.currentThread().getContextClassLoader().getResource(path);
    }

    @Override
    public List<URL> getApplicationResources(String path) throws IOException {
        return Collections.list(Thread.currentThread().getContextClassLoader().getResources(path));
    }

    @Override
    public URL getClientResource(String path) {
        return getApplicationResource(path);
    }

    @Override
    public InputStream getClientResourceAsStream(String path) throws IOException {
        final URL clientResource = getClientResource(path);
        return clientResource == null ? null : clientResource.openStream();
    }
}
```

**Comment by mvysny** [comment]
Fixed by implementing Undertow `ServletExtension` which forces Vaadin to load the token file from the filesystem. See the `VaadinServletExtension` class for more details.
